### ISSUE TITLE
OtherService3 can't be found

### ISSUE THREAD

**Issue by andybuki** [ksclarke/jiiify-presentation#117]
I try to create a manifest based on presentation API 3.0 and add field named behavior. 
import info.freelibrary.iiif.presentation.v3.services.OtherService3;
This class doesn't exist.

**Comment by andybuki** [comment]
i found OtherService instead OtherService3

**Comment by ksclarke** [comment]
If you're using the latest code from the repo, OtherService should be an interface that OtherService3 implements. You can see a simple example of OtherService3 in use at https://github.com/ksclarke/jiiify-presentation/blob/803b8a9c0dc82337586ec98894871dcf9b322f66/src/test/java/info/freelibrary/iiif/presentation/v3/ManifestTest.java#L159

If you're using a released/published version of the library though (from Maven Central), OtherService3 may not have made it to that yet. I don't consider the API stable until it hits version 1.0.0 (which I hope to hit by the end of this month). Until then there may be some API drift (breaking changes), just so you're aware...

Thanks for trying out the library, too, btw. I'm definitely interested in any pain points you experience when using it.  :-)

**Comment by ksclarke** [comment]
More specific service implementations (more specific than OtherService) are definitely in the works, too, btw. That's just intended as a fallback for things that don't have specific implementations (yet). Out of curiosity, which service are you using?
