### ISSUE TITLE
Make @context available on AnnotationPage

### ISSUE THREAD

**Issue by HenryH09** [ksclarke/jiiify-presentation#152]
Hello Kevin,

As per described in this cookbook recipe : 
https://iiif.io/api/cookbook/recipe/0269-embedded-or-referenced-annotations/
the "@context" property must be present for an external Annotation Page (i.e. supplementing annotations not embedded in the Manifest) but not if the Annotation Page is included within a Manifest (as the manifest will already have a @context property).
The value for the @context must then be "http://iiif.io/api/presentation/3/context.json".

I wasn't able to find a way to add the @context property using v0.10.1. We should be able to choose wether to include or not the @context property on an Annotation Page.

Thank you and best wishes for this new year !
Henry

**Comment by ksclarke** [comment]
Hi Henry, thanks for reporting. You're correct that I haven't really tackled external Annotation Page(s) yet. I'll go ahead and make this change and then update this ticket when done.

**Comment by HenryH09** [comment]
Thank you Kevin.

I am wrapping the AnnotationPage into a Spring ResponseEntity :
ResponseEntity<AnnotationPage<SupplementingAnnotation>>
The controller is set to produce JSON-LD (default) or JSON (if specified in Accept header). Jackson does the work here if I am not mistaken.

So I don't have an explicit difference when building an AnnotationPage to be included in a manifest and building an External AnnotationPage.

I am not sure what would be the best solution here, especially for maintaining an overall coherence. 
Maybe simply having a context property (null by default) on the AnnotationPage object with a Jackson "include if not null", and a method to set the static value for the context like "setExternalAnnotationPageContext()" (no custom value setter) that we will have to call when building an AnnotationPage object for external use ?

**Comment by ksclarke** [comment]
Thanks, Henry, for the additional details.

It's interesting to hear, too, about the value of Jackson for you. I have been experimenting some with the idea of removing that as a dependency (for use in environments that aren't as reflection friendly), so it's useful to know that that sort of thing would have a negative impact on folks who are implicitly relying on Jackson for the serialization. I'll keep that in mind.

As for the immediate change, I like your idea of how to implement it. I'll do that. Thanks.

On that, I wonder if there is any value in being able to unset that as well, perhaps <code>setExternalContext(boolean)</code>. I could also do <code>setExternalContext()</code> and <code>removeExternalContext()</code>. Do you have any preferences or opinions on which would be preferable?

**Comment by HenryH09** [comment]
I thought about a boolean way to achieve this but I feel it is not really coherent with the rest.

I think using `setExternalContext()` and `removeExternalContext()` to be more in line with the rest of the library and to be sufficiently self-explanatory.

**Comment by ksclarke** [comment]
Hi @HenryH09 

I've merged a commit that I believe implements this. Would you be interested in testing it out from the v3 branch source before I release a new 0.11.0 version? No pressure if you're busy with other things at the moment...

Thanks,
Kevin

**Comment by HenryH09** [comment]
Hi @ksclarke 

I tried to test the latest commit but I am having an issue with the package `info.freelibrary.util.warnings.(*)`
It seems to be missing even with a successful Maven build. Is it a generated package ?

Thanks,
Henry

**Comment by ksclarke** [comment]
Thanks, Henry, I'll take a look this week.

**Comment by ksclarke** [comment]
Oh, you said "even with a successful build" ... where do you see the issue if the build succeeded? Or do you mean just the compile phase of the build?

**Comment by HenryH09** [comment]
Yes, I am on the v3 branch using OpenJDK-11.0.9.11. 
Sorry I have been experiencing a lot of issues with my Eclipse(2019-12)/maven plugin(3.6.3) recently so I didn't look in the right direction...
The issue is actually coming from an outdated lib in the POM :
`<freelib.utils.version>2.4.0</freelib.utils.version>`  should be `<freelib.utils.version>3.0.1</freelib.utils.version>` 
It does solve the issue with the missing `info.freelibrary.util.warnings.(*)` package.

I have also upgraded `<freelib.maven.version>0.2.1</freelib.maven.version>` to `<freelib.maven.version>0.3.0</freelib.maven.version>` in my tests.

It does work correctly now and the PR#153 with the updated POM does show `@context` on an external AnnotationPage and not if embedded within a Manifest.

Thank You

**Comment by ksclarke** [comment]
Hmm, they should be there in 2.4.0 too: https://javadoc.io/doc/info.freelibrary/freelib-utils/2.4.0/info/freelibrary/util/warnings/package-summary.html but there is no harm in updating to the latest so I'll do that too.

Despite being an Eclipse user, too, I mostly run `mvn` from the command line -- the eclipse maven plugin has always seemed a little wonky to me. Maybe it's doing some caching or something and the version upgrade cleared it?

Anyway, thanks for confirming...

**Comment by ksclarke** [comment]
Released new version with updates -> https://repo1.maven.org/maven2/info/freelibrary/jiiify-presentation-v3/0.11.0/
