### ISSUE TITLE
Access cookie service URI isn't required for external interaction pattern

### ISSUE THREAD

**Issue by markmatney** [ksclarke/jiiify-presentation#155]
[Currently](https://github.com/ksclarke/jiiify-presentation/blob/c079e5fc1c5db64e6c20954b2753c2cd8fcc3c33/src/main/java/info/freelibrary/iiif/presentation/v3/services/auth/AuthCookieService1.java), it is required to supply an ID to instantiate an AuthCookieService1, but [the spec](https://iiif.io/api/auth/1.0/#external-interaction-pattern) doesn't require IDs for the external interaction pattern (and in fact instructs clients to ignore if present):

> There is no access cookie service. Any URI specified in the id property must be ignored.

A workaround for now is to provide a dummy ID e.g. `http://example.com`, since clients are required to ignore it. Of course, the current implementation is still spec compliant, but it would be nice to not have to provide an ID in cases where it isn't required.

**Comment by ksclarke** [comment]
So, we could just provide a constructor without the ID, but maybe it would be better to have an ExternalAuthCookieService1, etc., to treat them differently?

**Comment by markmatney** [comment]
Sure. Each interaction pattern as a type makes sense to me

**Comment by ksclarke** [comment]
Updated.
