### ISSUE TITLE
info.freelibrary.iiif.presentation.v3.properties.Start - Jackson produced JSON includes null Optional values

### ISSUE THREAD

**Issue by HenryH09** [ksclarke/jiiify-presentation#174]
Hello Kevin,

I have an issue with the **Start** element of the manifest.
In the case we create a start element with just an URI, this will add by default the "Canvas" type, which is expected, but then Jackson will add as well the two properties "selector" and "source" with a null value in the resulting JSON. Those should only be specified with a "SpecificResource" type.

You are using a `@JsonInclude(Include.NON_NULL)` Jackson annotation on those properties that will not work well with Java.util.Optional.
Using `@JsonInclude(Include.NON_ABSENT)` should do the trick as mentioned in the Javadoc :
> "absent" value of a referential type (like Java 8 `Optional`, or {link java.util.concurrent.atomic.AtomicReference}); that is, something that would not deference to a non-null value.

Thanks,
Henry

**Comment by ksclarke** [comment]
Thanks @HenryH09 for reporting this. Can you give me a little more details on how it's being used?

I don't see them come out in my test (https://github.com/ksclarke/jiiify-presentation/blob/988d6cb207b74e0d81b05236b42fd961000d13ec/src/test/java/info/freelibrary/iiif/presentation/v3/properties/StartTest.java#L34) because that uses the JSON util, which has absents treated as nulls: https://github.com/ksclarke/jiiify-presentation/blob/988d6cb207b74e0d81b05236b42fd961000d13ec/src/main/java/info/freelibrary/iiif/presentation/v3/utils/JSON.java#L33

So, I'm curious how it's being serialized without the JSON util. Do you have a test case you could share?

**Comment by ksclarke** [comment]
This isn't specific to your question, but just noting this discussion topic for myself because it's the same issue of serialization happening with the JSON util: https://github.com/ksclarke/jiiify-presentation/discussions/169

**Comment by HenryH09** [comment]
I am using implicit JSON serialization from Spring+Jackson.

My controller is returning a `ResponseEntity<Manifest>`
and the start element is simply added with a URI : `manifest.setStart(new Start("PRE_CALCULATED_URI_HERE"));`

To test it I did a simple ObjectMapper : 
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new Jdk8Module());
Start startJiiify = new Start("http://localhost:8080");
System.out.println(objectMapper.writeValueAsString(startJiiify));
```
With NON_NULL I have the selector and source value present and with a null value.
Changing to NON_ABSENT I will only have the id and type with their correct values.

**Comment by ksclarke** [comment]
Forgive the probably simple question, but I'm not a Spring user... with this method, you'll miss out on the float serializer. Is there a way I can support this for your use case? I can make the change to NON_ABSENT. I assume you're only doing it this way for serialization and not deserialization?

**Comment by ksclarke** [comment]
Actually, not having the float serializer may not be that consequential for you. For me, it helps roundtrip JSON so I can use the cookbooks as test resources. It's more of a nicety for the output than it is a functionality. I have the NON_ABSENT fix in PR #175. I'll go ahead and merge that and do a bug fix release later this evening.

**Comment by ksclarke** [comment]
Version 0.12.3 should fix this.

**Comment by HenryH09** [comment]
Thank you, Version 0.12.3 does fix the issue.
Indeed I am not doing any deserialization, I am only making manifests available and I don't have float values in the manifest so I didn't see that issue.
