### ISSUE TITLE
Support for Api extension "TextGranularity" within supplementing annotations

### ISSUE THREAD

**Issue by HenryH09** [ksclarke/jiiify-presentation#185]
Hello Kevin,

Would it be possible to add the Text-Granularity property on supplementing annotations as specified below ?
https://iiif.io/api/extension/text-granularity/#2-text-granularity-levels-and-the-textgranularity-property

Thank you,
Henry

**Comment by ksclarke** [comment]
Hi Henry, I'm heading out of town for the weekend, but did a quick addition. New version is 0.12.4. Will fix any issues with it next week.

**Comment by ksclarke** [comment]
Okay, just confirmed the deserialization works too. I still have to port it over to the v3 branch for going forward with the new annotation stuff, but 0.12.4 has it and is available from Maven Central now.
