### ISSUE TITLE
Consider using level 2 for ImageService default compliance level

### ISSUE THREAD

**Issue by markmatney** [ksclarke/jiiify-presentation#78]
While using this library for the first time in a while, I was surprised that the default compliance level is not level 2. My sense is that level 2 is the most common, and this seems to be supported by both [a 2018 survey](https://training.iiif.io/iiif-online-workshop/day-two/image-servers/#getting-started-with-the-image-api) (60% of respondents chose IIPImage or Loris, both of which implement level 2) and [by the current edition of this online workshop](https://training.iiif.io/iiif-online-workshop/day-two/image-servers/#iiif-image-server) ("Main ones", including Cantaloupe which also implements level 2).

**Comment by ksclarke** [comment]
Thanks for the references. I was thinking level 0 was the lowest common denominator, but the path of "least surprise" is important.

**Comment by markmatney** [comment]
oops, that second link was incorrect earlier -- fixed now
