### ISSUE TITLE
Add (String, Label) constructor to resource classes

### ISSUE THREAD

**Issue by markmatney** [ksclarke/jiiify-presentation#79]
While experimenting with this library, I found myself wanting to create Manifests and Canvases by passing IDs as Strings rather than URIs, along with Labels (so that a language could be specified, rather than defaulting to `"none"`).

**Comment by ksclarke** [comment]
The original thought was if you're using a Label instead of text you're probably okay with supplying a URI too. I can see the case for this change, though. I'll add the constructor, thanks.
